ALTER TABLE cash_cuts ADD COLUMN IF NOT EXISTS "openingCash" NUMERIC DEFAULT 0;
ALTER TABLE cash_cuts ADD COLUMN IF NOT EXISTS "cardTotal" NUMERIC DEFAULT 0;
ALTER TABLE cash_cuts ADD COLUMN IF NOT EXISTS "transferTotal" NUMERIC DEFAULT 0;
ALTER TABLE cash_cuts ADD COLUMN IF NOT EXISTS "creditTotal" NUMERIC DEFAULT 0;
ALTER TABLE cash_cuts ADD COLUMN IF NOT EXISTS "creditPayments" NUMERIC DEFAULT 0;
ALTER TABLE cash_cuts ADD COLUMN IF NOT EXISTS "orderPayments" NUMERIC DEFAULT 0;
ALTER TABLE cash_cuts ADD COLUMN IF NOT EXISTS "cashExpenses" NUMERIC DEFAULT 0;
ALTER TABLE cash_cuts ADD COLUMN IF NOT EXISTS "cashRefunds" NUMERIC DEFAULT 0;
